version: "3.8"

services:
  backend:
    build:
      context: ./mental_health_survey_be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./mental_health_survey_be:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - ./mental_health_survey_be/.env
    environment:
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:reset_and_seed && bundle exec rails s -b 0.0.0.0"

  frontend:
    build:
      context: ./mental_health_survey_fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  bundle_cache:
